# Default values for total_invoice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replica_count: 1
namespace: total-invoice

# If set to "console", the logs will be captured from stdout/stderr
# instead of assuming that the service will be pushing them using HTTP
log_capture_mode: http

# In production environment the auth token should not have a default value
# (it should be passed via command-line parameter at deployment time)
auth_token: letmeinpleasekthxbye

invoices_svc_image: invoices_svc:v1
expected_date_svc_image: expected_date_svc:v1
auth_svc_image: auth_svc:v1
ambassador_svc_image: quay.io/datawire/ambassador:0.34.0
ambassador_svc_statsd_image: quay.io/datawire/statsd:0.34.0
fluentdsidecar_image: atcdemo.azurecr.io/fluentdsidecar:latest
