# Default values for total_invoice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replica_count: 1
namespace: total-invoice

# This should really be a secret, but for the sake of keeping the example very simple
# we are going to just use an ordinary value for now.
auth_token: letmeinpleasekthxbye

invoices_svc_image: invoices_svc:v1
expected_date_svc_image: expected_date_svc:v1
auth_svc_image: auth_svc:v1
ambassador_svc_image: quay.io/datawire/ambassador:0.34.0
ambassador_svc_statsd_image: quay.io/datawire/statsd:0.34.0
