{{- $service_name := "expected-date-svc" }}
{{- $context := (dict "service_name" $service_name "Values" .Values "Release" .Release) }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "total_invoice.std.labels" $context | indent 4 }}
  name: {{ $service_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
{{ include "total_invoice.std.labels" $context | indent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "total_invoice.std.labels" $context | indent 8 }}
    spec:
      containers:
      - image: {{ .Values.expected_date_svc_image }}
        imagePullPolicy: Always
        name: {{ $service_name }}
        ports:
        - containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "total_invoice.std.labels" $context | indent 4 }}
  name: {{ $service_name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
{{ include "total_invoice.std.labels" $context | indent 4 }}
