apiVersion: v1
kind: Secret
metadata:
  name: total-invoice-secrets
  app: total-invoice
  release: {{ .Release.Name }}
type: Opaque
data:
  appinsights_instrumentationkey: {{ .Values.appinsights_instrumentationkey | b64enc }}
  auth_token: {{ .Values.auth_token | b64enc }}